version: '3'

services:
  neo-db:
    build:
      context: ./db
      dockerfile: Dockerfile
    environment:
      - NEO4J_DEBUG:yes
      - NEO4J_ACCEPT_LICENSE_AGREEMENT:yes
      - NEO4J_AUTH=neo4j/${NEO4j_SECRET}
      - NEO4J_apoc_export_file_enabled=true
      - NEO4J_apoc_import_file_enabled=true
      - NEO4J_apoc_import_file_use__neo4j__config=true
      - NEO4J_PLUGINS=["apoc", "graph-data-science"]
      - NEO4J_server_config_strict__validation_enabled=false
      - dbms.directories.import="/"
    ports:
      - "7474:7474"  # Map Neo4j database port     
      - "7687:7687"  # Map Neo4j database port  
      - "7473:7473"  # Map Neo4j database port  
    networks:
      - remix-network
    volumes:
      - neo4j-data:/data
  remix-app:
    build:
      context: .
      dockerfile: Dockerfile
    image: remix-app
    container_name: remix-container
    ports:
      - "5173:5173"
    volumes:
      - ./app:/App/app
      - ./public:/App/public
      - ./styles:/App/styles
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true
      - NEO4j_SECRET=${NEO4j_SECRET}
    networks:
      - remix-network
    depends_on:
      - neo-db


volumes:
  neo4j-data:
    name: neo4j-graph-db
  


networks:
  remix-network:
    driver: bridge
